version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: study_dashboard
      MONGO_INITDB_ROOT_PASSWORD: study_dashboard
      MONGO_INITDB_DATABASE: study_dashboard
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  backend:
    driver: bridge