spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secrets: asdnfkqwlnfsladdfhbnoisadhfoklqsbdnfohsaodfqwe
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2